# Project information
site_name: Monkey Docs
site_url: https://aapman55.github.io/MonkeyDocs/
site_author: aapman
site_description: >-
  This is not a resource site. Just a brain dump of useful stuff
  for tools I encounter.

# Copyright
copyright: Copyright &copy; 2021 Aapman

# Theme
theme:
  name: material
  logo: assets/images/monkeyDocsLogo.png
  favicon: assets/images/monkeyDocsLogo.png
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  custom_dir: overrides

use_directory_urls: true

# Enable pencil icon to directly modify page
repo_name: aapman55/MonkeyDocs
repo_url: https://github.com/aapman55/MonkeyDocs
edit_uri: edit/main/docs/

# Plugins
plugins:
  - search

markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.details
  - admonition
  - meta
  - footnotes
  - tables
  - toc:
      permalink: true
      toc_depth: 3

# Page tree
nav:
  - Home: index.md
  - Data Engineering and analysis:
    -  Data_Engineering_Analysis/index.md
    - Architecture:
      - Data_Engineering_Analysis/Architecture/index.md
      - Idempotence: Data_Engineering_Analysis/Architecture/idempotence.md
    - Microsoft:
        - SQL server:
          - Indexes: Data_Engineering_Analysis/Microsoft/SQL_server/indexes.md
          - Recommended server settings: Data_Engineering_Analysis/Microsoft/SQL_server/recommended_server_settings.md
          - Useful scripts:
            - Generate Queries using Templates: Data_Engineering_Analysis/Microsoft/SQL_server/useful_scripts/GenerateTemplatedQueries.md
            - Query SSIS package contents: Data_Engineering_Analysis/Microsoft/SQL_server/useful_scripts/QuerySSISPackages.md
            - Query group members: Data_Engineering_Analysis/Microsoft/SQL_server/useful_scripts/GroupMembersQuery.md
            - Query SQL Dependencies: Data_Engineering_Analysis/Microsoft/SQL_server/useful_scripts/SQLdependencies.md
          - Helpful resources: Data_Engineering_Analysis/Microsoft/SQL_server/helpful_resources.md
    - Python:
      - Helpful resources: Data_Engineering_Analysis/Python/helpful_resources.md
    - Spark:
      - Data_Engineering_Analysis/spark/index.md
      - Recommended spark conf: Data_Engineering_Analysis/spark/recommended_spark_conf.md
  - Productivity Tools:
    - Productivity/index.md
  - Ideas bucket:
    - ideas_bucket/index.md
