site_name: Monkey Docs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Enable pencil icon to directly modify page
repo_name: aapman55/MonkeyDocs
repo_url: https://github.com/aapman55/MonkeyDocs
edit_uri: edit/main/docs/

# Plugins
plugins:
  - search

markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - meta
  - footnotes
  - toc:
      permalink: true
      toc_depth: 5

# Page tree
nav:
  - Microsoft:
      - SQL server:
        - Useful scripts:
          - Query group members: Microsoft/SQL_server/useful_scripts/GroupMembersQuery.md

